--1.
USE [master]
GO

/****** Object:  Database [RandomCompany]    Script Date: 5/12/2021 7:55:27 AM ******/
CREATE DATABASE [RandomCompany]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'RandomCompany', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\RandomCompany.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'RandomCompany_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\RandomCompany_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RandomCompany].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [RandomCompany] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [RandomCompany] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [RandomCompany] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [RandomCompany] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [RandomCompany] SET ARITHABORT OFF 
GO

ALTER DATABASE [RandomCompany] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [RandomCompany] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [RandomCompany] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [RandomCompany] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [RandomCompany] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [RandomCompany] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [RandomCompany] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [RandomCompany] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [RandomCompany] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [RandomCompany] SET  DISABLE_BROKER 
GO

ALTER DATABASE [RandomCompany] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [RandomCompany] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [RandomCompany] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [RandomCompany] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [RandomCompany] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [RandomCompany] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [RandomCompany] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [RandomCompany] SET RECOVERY FULL 
GO

ALTER DATABASE [RandomCompany] SET  MULTI_USER 
GO

ALTER DATABASE [RandomCompany] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [RandomCompany] SET DB_CHAINING OFF 
GO

ALTER DATABASE [RandomCompany] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [RandomCompany] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [RandomCompany] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [RandomCompany] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [RandomCompany] SET QUERY_STORE = OFF
GO

ALTER DATABASE [RandomCompany] SET  READ_WRITE 
GO


USE [RandomCompany]
GO
/****** Object:  Table [dbo].[Address]    Script Date: 5/12/2021 7:51:40 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Address](
	[AddressID] [int] NOT NULL,
	[AddressLine] [nvarchar](50) NULL,
	[AddressLine2] [nchar](10) NULL,
	[PostalCode] [nchar](10) NULL,
	[CityId] [int] NULL,
 CONSTRAINT [PK_Address] PRIMARY KEY CLUSTERED 
(
	[AddressID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[City]    Script Date: 5/12/2021 7:51:40 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[City](
	[CityID] [int] NOT NULL,
	[CityName] [nvarchar](50) NULL,
	[CountryName] [nvarchar](50) NULL,
	[Inhabitants] [nvarchar](50) NULL,
 CONSTRAINT [PK_City] PRIMARY KEY CLUSTERED 
(
	[CityID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Employee]    Script Date: 5/12/2021 7:51:40 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Employee](
	[EmployeeID] [int] NOT NULL,
	[FirstName] [nvarchar](50) NULL,
	[LastName] [nvarchar](50) NULL,
	[Salary] [decimal](6, 2) NULL,
	[CityID] [int] NULL,
	[AddressID] [int] NULL,
 CONSTRAINT [PK_Employee] PRIMARY KEY CLUSTERED 
(
	[EmployeeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Office]    Script Date: 5/12/2021 7:51:40 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Office](
	[OfficeID] [int] NOT NULL,
	[Name] [nvarchar](50) NULL,
	[AddressID] [int] NULL,
	[DirectorID] [int] NULL,
	[HeadOfficeID] [int] NULL,
	[Tel] [nvarchar](50) NULL,
 CONSTRAINT [PK_Office] PRIMARY KEY CLUSTERED 
(
	[OfficeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [IX_Office] UNIQUE NONCLUSTERED 
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [IX_Office_1] UNIQUE NONCLUSTERED 
(
	[AddressID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Project]    Script Date: 5/12/2021 7:51:40 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Project](
	[ProjectID] [int] NOT NULL,
	[ManagerID] [int] NULL,
	[OfficeID] [int] NULL,
 CONSTRAINT [PK_Project] PRIMARY KEY CLUSTERED 
(
	[ProjectID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ProjectDetail]    Script Date: 5/12/2021 7:51:40 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ProjectDetail](
	[ProjectDetailID] [int] NOT NULL,
	[Title] [nvarchar](50) NULL,
	[Budget] [decimal](10, 2) NULL,
	[StartDate] [date] NULL,
	[EndDate] [date] NULL,
	[ProjectID] [int] NULL,
	[CityID] [int] NULL,
 CONSTRAINT [PK_ProjectDetail] PRIMARY KEY CLUSTERED 
(
	[ProjectDetailID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Address]  WITH CHECK ADD  CONSTRAINT [FK_Address_City] FOREIGN KEY([AddressID])
REFERENCES [dbo].[City] ([CityID])
GO
ALTER TABLE [dbo].[Address] CHECK CONSTRAINT [FK_Address_City]
GO
ALTER TABLE [dbo].[Employee]  WITH CHECK ADD  CONSTRAINT [FK_Employee_Address] FOREIGN KEY([AddressID])
REFERENCES [dbo].[Address] ([AddressID])
GO
ALTER TABLE [dbo].[Employee] CHECK CONSTRAINT [FK_Employee_Address]
GO
ALTER TABLE [dbo].[Employee]  WITH CHECK ADD  CONSTRAINT [FK_Employee_City] FOREIGN KEY([CityID])
REFERENCES [dbo].[City] ([CityID])
GO
ALTER TABLE [dbo].[Employee] CHECK CONSTRAINT [FK_Employee_City]
GO
ALTER TABLE [dbo].[Office]  WITH CHECK ADD  CONSTRAINT [FK_Office_Address] FOREIGN KEY([AddressID])
REFERENCES [dbo].[Address] ([AddressID])
GO
ALTER TABLE [dbo].[Office] CHECK CONSTRAINT [FK_Office_Address]
GO
ALTER TABLE [dbo].[Office]  WITH CHECK ADD  CONSTRAINT [FK_Office_Employee] FOREIGN KEY([DirectorID])
REFERENCES [dbo].[Employee] ([EmployeeID])
GO
ALTER TABLE [dbo].[Office] CHECK CONSTRAINT [FK_Office_Employee]
GO
ALTER TABLE [dbo].[Office]  WITH CHECK ADD  CONSTRAINT [FK_Office_HeadOffice] FOREIGN KEY([HeadOfficeID])
REFERENCES [dbo].[Office] ([OfficeID])
GO
ALTER TABLE [dbo].[Office] CHECK CONSTRAINT [FK_Office_HeadOffice]
GO
ALTER TABLE [dbo].[Project]  WITH CHECK ADD  CONSTRAINT [FK_Project_Employee] FOREIGN KEY([ProjectID])
REFERENCES [dbo].[Employee] ([EmployeeID])
GO
ALTER TABLE [dbo].[Project] CHECK CONSTRAINT [FK_Project_Employee]
GO
ALTER TABLE [dbo].[ProjectDetail]  WITH CHECK ADD  CONSTRAINT [FK_ProjectDetail_City] FOREIGN KEY([CityID])
REFERENCES [dbo].[City] ([CityID])
GO
ALTER TABLE [dbo].[ProjectDetail] CHECK CONSTRAINT [FK_ProjectDetail_City]
GO
ALTER TABLE [dbo].[ProjectDetail]  WITH CHECK ADD  CONSTRAINT [FK_ProjectDetail_Project] FOREIGN KEY([ProjectDetailID])
REFERENCES [dbo].[Project] ([ProjectID])
GO
ALTER TABLE [dbo].[ProjectDetail] CHECK CONSTRAINT [FK_ProjectDetail_Project]
GO
--2.
USE [master]
GO

/****** Object:  Database [Lending]    Script Date: 5/12/2021 7:55:01 AM ******/
CREATE DATABASE [Lending]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Lending', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Lending.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Lending_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Lending_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Lending].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Lending] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Lending] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Lending] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Lending] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Lending] SET ARITHABORT OFF 
GO

ALTER DATABASE [Lending] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Lending] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Lending] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Lending] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Lending] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Lending] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Lending] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Lending] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Lending] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Lending] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Lending] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Lending] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Lending] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Lending] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Lending] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Lending] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Lending] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Lending] SET RECOVERY FULL 
GO

ALTER DATABASE [Lending] SET  MULTI_USER 
GO

ALTER DATABASE [Lending] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Lending] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Lending] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Lending] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Lending] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Lending] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Lending] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Lending] SET  READ_WRITE 
GO


USE [Lending]
GO
/****** Object:  Table [dbo].[Borrower]    Script Date: 5/12/2021 7:52:37 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Borrower](
	[BorrowerID] [int] NOT NULL,
	[ContactID] [int] NULL,
	[RiskValue] [int] NULL,
 CONSTRAINT [PK_Borrower] PRIMARY KEY CLUSTERED 
(
	[BorrowerID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Contact]    Script Date: 5/12/2021 7:52:38 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Contact](
	[ContactID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](10) NOT NULL,
	[Title] [nvarchar](30) NULL,
	[TitleOfCourtesy] [nvarchar](25) NULL,
	[BirthDate] [datetime] NULL,
	[Address] [nvarchar](60) NULL,
	[City] [nvarchar](15) NULL,
	[Region] [nvarchar](15) NULL,
	[PostalCode] [nvarchar](10) NULL,
	[Country] [nvarchar](15) NULL,
	[ContactPhone] [nvarchar](24) NULL,
	[Notes] [ntext] NULL,
 CONSTRAINT [PK_Employees] PRIMARY KEY CLUSTERED 
(
	[ContactID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Lender]    Script Date: 5/12/2021 7:52:38 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Lender](
	[LenderID] [int] NOT NULL,
	[AvailableAmount] [decimal](10, 2) NULL,
	[ContactID] [int] NULL,
 CONSTRAINT [PK_Lender] PRIMARY KEY CLUSTERED 
(
	[LenderID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Loan]    Script Date: 5/12/2021 7:52:38 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Loan](
	[LoanID] [int] NOT NULL,
	[Amount] [decimal](12, 2) NULL,
	[Deadline] [date] NULL,
	[InterestRate] [int] NULL,
	[Purpose] [nvarchar](50) NULL,
	[BorrowerID] [int] NULL,
 CONSTRAINT [PK_Loan] PRIMARY KEY CLUSTERED 
(
	[LoanID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LoanDeatail]    Script Date: 5/12/2021 7:52:38 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LoanDeatail](
	[LoanDetailID] [int] NOT NULL,
	[LenderID] [int] NULL,
	[PartialAmount] [decimal](10, 2) NULL,
	[LoanID] [int] NULL,
 CONSTRAINT [PK_LoanDeatail] PRIMARY KEY CLUSTERED 
(
	[LoanDetailID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Borrower]  WITH CHECK ADD  CONSTRAINT [FK_Borrower_Contact] FOREIGN KEY([ContactID])
REFERENCES [dbo].[Contact] ([ContactID])
GO
ALTER TABLE [dbo].[Borrower] CHECK CONSTRAINT [FK_Borrower_Contact]
GO
ALTER TABLE [dbo].[Lender]  WITH CHECK ADD  CONSTRAINT [FK_Lender_Contact] FOREIGN KEY([ContactID])
REFERENCES [dbo].[Contact] ([ContactID])
GO
ALTER TABLE [dbo].[Lender] CHECK CONSTRAINT [FK_Lender_Contact]
GO
ALTER TABLE [dbo].[Loan]  WITH CHECK ADD  CONSTRAINT [FK_Loan_Borrower] FOREIGN KEY([LoanID])
REFERENCES [dbo].[Borrower] ([BorrowerID])
GO
ALTER TABLE [dbo].[Loan] CHECK CONSTRAINT [FK_Loan_Borrower]
GO
ALTER TABLE [dbo].[LoanDeatail]  WITH CHECK ADD  CONSTRAINT [FK_LoanDeatail_Lender] FOREIGN KEY([LenderID])
REFERENCES [dbo].[Lender] ([LenderID])
GO
ALTER TABLE [dbo].[LoanDeatail] CHECK CONSTRAINT [FK_LoanDeatail_Lender]
GO
ALTER TABLE [dbo].[LoanDeatail]  WITH CHECK ADD  CONSTRAINT [FK_LoanDeatail_Loan] FOREIGN KEY([LoanID])
REFERENCES [dbo].[Loan] ([LoanID])
GO
ALTER TABLE [dbo].[LoanDeatail] CHECK CONSTRAINT [FK_LoanDeatail_Loan]
GO
--3.
USE [master]
GO

/****** Object:  Database [Resturant]    Script Date: 5/12/2021 7:54:26 AM ******/
CREATE DATABASE [Resturant]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Resturant', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Resturant.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Resturant_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Resturant_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Resturant].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Resturant] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Resturant] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Resturant] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Resturant] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Resturant] SET ARITHABORT OFF 
GO

ALTER DATABASE [Resturant] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Resturant] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Resturant] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Resturant] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Resturant] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Resturant] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Resturant] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Resturant] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Resturant] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Resturant] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Resturant] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Resturant] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Resturant] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Resturant] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Resturant] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Resturant] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Resturant] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Resturant] SET RECOVERY FULL 
GO

ALTER DATABASE [Resturant] SET  MULTI_USER 
GO

ALTER DATABASE [Resturant] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Resturant] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Resturant] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Resturant] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Resturant] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Resturant] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Resturant] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Resturant] SET  READ_WRITE 
GO


USE [Resturant]
GO
/****** Object:  Table [dbo].[Category]    Script Date: 5/12/2021 7:53:07 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Category](
	[CategoryID] [int] NOT NULL,
	[Name] [nvarchar](50) NULL,
	[Brief] [nvarchar](50) NULL,
	[EmployeeID] [int] NULL,
 CONSTRAINT [PK_Category] PRIMARY KEY CLUSTERED 
(
	[CategoryID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Course]    Script Date: 5/12/2021 7:53:07 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Course](
	[CourseID] [int] NOT NULL,
	[Name] [nvarchar](50) NULL,
	[Breif] [nvarchar](50) NULL,
	[PhotoPath] [nvarchar](50) NULL,
	[FinalPrice] [decimal](6, 2) NULL,
	[CategoryID] [int] NULL,
	[RecipeID] [int] NULL,
 CONSTRAINT [PK_Course] PRIMARY KEY CLUSTERED 
(
	[CourseID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Employee]    Script Date: 5/12/2021 7:53:07 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Employee](
	[EmployeeID] [int] IDENTITY(1,1) NOT NULL,
	[LastName] [nvarchar](20) NOT NULL,
	[FirstName] [nvarchar](10) NOT NULL,
	[Title] [nvarchar](30) NULL,
	[TitleOfCourtesy] [nvarchar](25) NULL,
	[BirthDate] [datetime] NULL,
	[Address] [nvarchar](60) NULL,
	[City] [nvarchar](15) NULL,
	[Region] [nvarchar](15) NULL,
	[PostalCode] [nvarchar](10) NULL,
	[Country] [nvarchar](15) NULL,
	[HomePhone] [nvarchar](24) NULL,
	[Extension] [nvarchar](4) NULL,
	[Photo] [image] NULL,
	[Notes] [ntext] NULL,
	[PhotoPath] [nvarchar](255) NULL,
 CONSTRAINT [PK_Employees] PRIMARY KEY CLUSTERED 
(
	[EmployeeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Ingredient]    Script Date: 5/12/2021 7:53:07 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Ingredient](
	[IngredientID] [int] NOT NULL,
	[Name] [nvarchar](50) NULL,
	[Unit] [nvarchar](50) NULL,
	[Stock] [int] NULL,
 CONSTRAINT [PK_Ingredient] PRIMARY KEY CLUSTERED 
(
	[IngredientID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Receipe]    Script Date: 5/12/2021 7:53:07 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Receipe](
	[RecipeID] [int] NOT NULL,
	[PreparationTime] [int] NULL,
	[CookingTime] [int] NULL,
	[Difficulty] [int] NULL,
	[Description] [nvarchar](50) NULL,
 CONSTRAINT [PK_Receipe] PRIMARY KEY CLUSTERED 
(
	[RecipeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[RecipeIngredient]    Script Date: 5/12/2021 7:53:07 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RecipeIngredient](
	[RecipeIngredientID] [int] NOT NULL,
	[Amount] [int] NULL,
	[ReceipeID] [int] NULL,
	[IngredientID] [int] NULL,
 CONSTRAINT [PK_RecipeIngredient] PRIMARY KEY CLUSTERED 
(
	[RecipeIngredientID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Category]  WITH CHECK ADD  CONSTRAINT [FK_Category_Employee] FOREIGN KEY([CategoryID])
REFERENCES [dbo].[Employee] ([EmployeeID])
GO
ALTER TABLE [dbo].[Category] CHECK CONSTRAINT [FK_Category_Employee]
GO
ALTER TABLE [dbo].[Course]  WITH CHECK ADD  CONSTRAINT [FK_Course_Category] FOREIGN KEY([CategoryID])
REFERENCES [dbo].[Category] ([CategoryID])
GO
ALTER TABLE [dbo].[Course] CHECK CONSTRAINT [FK_Course_Category]
GO
ALTER TABLE [dbo].[Course]  WITH CHECK ADD  CONSTRAINT [FK_Course_Receipe] FOREIGN KEY([CourseID])
REFERENCES [dbo].[Receipe] ([RecipeID])
GO
ALTER TABLE [dbo].[Course] CHECK CONSTRAINT [FK_Course_Receipe]
GO
ALTER TABLE [dbo].[RecipeIngredient]  WITH CHECK ADD  CONSTRAINT [FK_RecipeIngredient_Ingredient] FOREIGN KEY([RecipeIngredientID])
REFERENCES [dbo].[Ingredient] ([IngredientID])
GO
ALTER TABLE [dbo].[RecipeIngredient] CHECK CONSTRAINT [FK_RecipeIngredient_Ingredient]
GO
ALTER TABLE [dbo].[RecipeIngredient]  WITH CHECK ADD  CONSTRAINT [FK_RecipeIngredient_Receipe] FOREIGN KEY([RecipeIngredientID])
REFERENCES [dbo].[Receipe] ([RecipeID])
GO
ALTER TABLE [dbo].[RecipeIngredient] CHECK CONSTRAINT [FK_RecipeIngredient_Receipe]
GO
